### ISSUE TITLE
players who join after game started are invisible except for the name tag on them

### ISSUE THREAD

**Issue by YourLocalIdiot123** [ANormalTwig/LC-LateCompany#44] opened 2024-07-27 09:19 UTC
basically, when a new person joins after the ship has landed once they are invisible except for the name tag that is on the suit

**Comment by Charlese2** [comment] 2024-08-03 00:37
That is caused by `PlayerControllerB.DisablePlayerModel` being ran on death but not being re-ran in `StartOfRound.ReviveDeadPlayers`. `ReviveDeadPlayers` will only run on connected players, so if someone dies and leaves the game, any player in that Player Controller slot will be invisible until it gets revived normally.

**Closed as completed** 2024-08-19 20:49 UTC
Labels: bug
