### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by evanw555** [ANormalTwig/LC-LateCompany#16] opened 2023-12-08 09:21 UTC
I'm trying to use this mod but have no idea how it's supposed to work. The "invite" menu option is still disabled even when this mod is installed. Is that normal? Is there some other way to invite others? When can they be invited? What is the behavior when invited mid-round? What's the expected behavior? Does this affect UI? etc. etc.

Please update your README file explaining this so I (and inevitably others) can determine if the problem is user error or mod error. That would help a lot, thanks.

**Comment by vgomasjaya** [comment] 2023-12-08 10:35
I have the same problem

**Comment by HeyBrab** [comment] 2023-12-10 08:39
I also have the same problem. Using Thunderstore and no other mods, nothing I do seems to make the mod work.

**Comment by ethanolzamboni** [comment] 2023-12-11 00:29
You can use the steam in-game overlay to invite by clicking on a  friends name, I don't know why the button in the menu is greyed out, but shift-tab invites work as intended.

**Comment by anormaltwig** [comment] 2023-12-11 19:30
fixed in 1.0.5

**Closed as completed by anormaltwig** 2023-12-11 19:30 UTC
Labels: bug
